services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      - POSTGRES_DB=atlasway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=atlasway
    ports:
      - "5435:5432"